---
title: "Climate Visualisations"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: united
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
```

## Temperature Index Plot

```{r Temperature Index Plot}

read_csv("data/GLB.Ts+dSST.csv", skip = 1, na = "***") %>% 
  select(year = Year, t_diff = `J-D`) %>% 
  drop_na() %>% 
  ggplot(aes(x = year, y = t_diff)) +
  geom_line(aes(colour = "1"), size = 0.5, show.legend = FALSE) +
  geom_point(fill = "white", aes(colour = "1"), shape = 21, show.legend = TRUE) +
  geom_smooth(se = FALSE, aes(colour = "2"), size = 0.5, span = 0.2, show.legend = FALSE) + 
  scale_x_continuous(breaks = seq(1880, 2023, 20), expand = c(0,0)) +
  scale_y_continuous(limits = c(-0.5, 1.5), expand = c(0,0)) +
  scale_colour_manual(name = NULL, breaks = c(1,2), values = c("gray", "black"), labels = c("Annual mean", "Loess smoothing"),
                      guide = guide_legend(override.aes = list(shape = 15, size = 5))) +
  labs(x = "", y = "Temperature Anomaly (C)",
       title = "GLOBAL LAND-OCEAN TEMPERATURE INDEX",
       subtitle = "Data source: NASA's Goddard Institute for Space Studies (GISS).\nCredit: NASA/GISS") +
  theme_light() +
  theme(axis.ticks = element_blank(),
        axis.title.y = element_text(size = 9),
        plot.title.position = "plot",
        plot.title = element_text(margin = margin(b = 10), colour = "red", face = "bold"),
        plot.subtitle = element_text(size = 8, margin = margin(b = 10)),
        legend.position = c(0.15, 0.9),
        legend.title = element_text(size = 0),
        legend.key.height = unit(10, "pt"),
        legend.margin = margin(0,0,0,0))
```

## Temperature Bar Plot

```{r Temperature Bar Plot}

t_data <- read_csv("data/GLB.Ts+dSST.csv", skip = 1, na ="***") %>%
  select(year = Year, t_diff = `J-D`) %>% 
  drop_na()

annotation <- t_data %>% 
  arrange(year) %>% 
  slice(1, n()) %>% 
  mutate(t_diff = 0,
         x = year + c(-5,5))

t_data %>% 
  ggplot(aes(x = year, y = t_diff, fill = t_diff)) +
  geom_col(show.legend = FALSE) +
  geom_text(data = annotation, aes(x = x, label = year), colour = "white") +
  geom_text(x = 1880, y = 1, hjust = 0,
            label = "Global Temperatures have increased by over 1.2\u00B0C since 1880",
            colour = "white") +
  scale_fill_stepsn(colours = c("darkblue", "white", "darkred"),
                    values = rescale(c(min(t_data$t_diff), 0, max(t_data$t_diff))),
                    limits = c(min(t_data$t_diff), max(t_data$t_diff)),
                    n.breaks = 9) +
  theme_void() +
  theme(plot.background = element_rect(fill = "black"))
```

